language: python
python:
  - "3.6.7"

services:
  - postgresql

# command to install dependencies
install:
  - pip install -r requirements.txt
before script:
  - psql -c 'create database testdb;' -U postgres
# command to run tests
script: 
  - pytest --cov=.
after_success:
  - coveralls